### ISSUE TITLE
[Request] Auto reconnect to rcon after server restart.

### ISSUE THREAD

**Issue by Keaft** [destruc7i0n/shulker#11]
My server restarts every night.

**Comment by destruc7i0n** [comment]
What you can do is `npm install -g forever` and then `forever start index.js`.

This will make it auto restart the script on crash :)

**Comment by Keaft** [comment]
Immediately implemented because that is just too dang useful in every situation.

However the script doesn't appear to crash on mc server shutdown. It just says:
[INFO] rcon disconnected

or something like that.

(I say not crashed because I still have to ctrl+c to return to terminal.)

**Comment by destruc7i0n** [comment]
Just add a `process.exit(1)` after line 23.

**Comment by Keaft** [comment]
Is it even legal to be that quick to a fix?
Thanks once again my man!
