### ISSUE TITLE
More detail in the wiki

### ISSUE THREAD

**Issue by BinaryCrafter** [destruc7i0n/shulker#18]
Would it be possible to have more detail added to the wiki? I'm trying to install Shulker Bot, and have managed to get it working one way (Discord -> MC), but not the reverse.

With reference to the tail command, the wiki says `make sure to replace your URL and your log directory location`, but what exactly is the URL? Where should it point to? Should this be a discordapp URL, or something on localhost?

Apologies if I'm missing something obvious, but I've been trying all sorts for the past few days and haven't been able to work out how it is supposed to be configured.

**Comment by destruc7i0n** [comment]
```
tail -F /PATH_TO_MINECRAFT_INSTALL/logs/latest.log | grep --line-buffered ": <" | while read x ; do echo -ne $x | curl -X POST -d @- http://YOUR_URL/minecraft/hook ; done
```

In the command below that line, there are places called `PATH_TO_MINECRAFT_INSTALL` and `YOUR_URL`. If you're running the node script on the same server, make `YOUR_URL` to localhost and the port specified in the config, by default `localhost:8000`. The `PATH_TO_MINECRAFT_INSTALL` should be the main location of the installation.

**Comment by BinaryCrafter** [comment]
Thanks destruc7ion, that makes sense to me now and have just had my first success. Much appreciated.
