### ISSUE TITLE
Extended functionality

### ISSUE THREAD

**Issue by 0x4323** [destruc7i0n/shulker#20]
Hope you don't mind me creating feature requests here, but I have a few ideas for additional messages that could be transmitted to Discord:

- Players Leaving & Joining
- Death Messages
- Achievement/Advancment Messages
- /me messages

**Comment by TheZackCodec** [comment]
@BinaryCrafter I already added some of those features in my forked version. I'm also working on the ability to allow certain discord users to run server commands.

**Comment by TheZackCodec** [comment]
Actually I'll add the achievement and death features in a pull request this weekend.  If it hasn't been too long since you requested the features like 2 years ago
