### ISSUE TITLE
What is wrong?

### ISSUE THREAD

**Issue by DrexHD** [destruc7i0n/shulker#22]
npm-debug.log

`0 info it worked if it ends with ok
1 verbose cli [ '/home/jannes/.nvm/versions/node/v4.4.7/bin/node',
1 verbose cli   '/home/jannes/.nvm/versions/node/v4.4.7/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart shulker@1.0.0
6 info start shulker@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info shulker@1.0.0 Failed to exec start script
9 verbose stack Error: shulker@1.0.0 start: `node index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/home/jannes/.nvm/versions/node/v4.4.7/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/home/jannes/.nvm/versions/node/v4.4.7/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid shulker@1.0.0
11 verbose cwd /home/jannes/shulker-master
12 error Linux 3.16.0-4-amd64
13 error argv "/home/jannes/.nvm/versions/node/v4.4.7/bin/node" "/home/jannes/.nvm/versions/node/v4.4.7/bin/npm" "start"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error shulker@1.0.0 start: `node index.js`
17 error Exit status 1
18 error Failed at the shulker@1.0.0 start script 'node index.js'.
18 error This is most likely a problem with the shulker package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs shulker
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls shulker
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]`

**Comment by destruc7i0n** [comment]
Can you try Node 6 or 8.
