### ISSUE TITLE
Discord Webhook

### ISSUE THREAD

**Issue by Kore-Development** [destruc7i0n/shulker#25]
Could you please use this JSON for the message on Discord using a webhook and content type `application/json`? Just replace `Notch` with the username and `Example message` with the message.
```
{
"content": "Example message",
"username": "Notch",
"avatar_url": "https://minotar.net/helm/Notch/300.png"
}
```
If you use the JSON it would show up as
![](https://i.gyazo.com/5084efc184c67f0a06b23a5610f47c72.png)

**Comment by destruc7i0n** [comment]
Hey there! Really sorry for the late response, but I added support for this (finally) in the latest update!
