### ISSUE TITLE
Tellraw escape

### ISSUE THREAD

**Issue by XmiliaH** [destruc7i0n/shulker#34]
First of all, I didn't test these. But I wondered where " is escaped from discord to minecraft messages. I didn't find a place, so you can escape the tellraw json and add styles with clickable links & commands.
Also it should be possible to send § from discord to minecraft.
From minecraft to discord @here & @everyone should be escaped. Normally the bots shouldn't have perms to mention everyone, but I saw servers giving the Bots roll Admin permissions.
I'm sorry if these are already handled somewhere and I oversaw it.

**Comment by destruc7i0n** [comment]
Ah, these are good points you've brought up. I used to use `JSON.stringify` but an update made it simply use `.replace`, which doesn't escape it, will need to get a fix for that... As for the mentions part, I actually used to use that as a feature, but it would be good to be an option for people working out of the box, I'll do that at some point.

**Comment by CactusOwnage** [comment]
The bot is still able to mention @everyone and @here without having the permission to mention when creating the invite link, and also having mention disabled in the channel for me. Forgive me for asking, am I still missing something or is this a bug?

**Comment by Heath123** [comment]
It's because you're using a webhook. It should be easy enough to fix in the code by adding `.replace("@everyone", "@ everyone").replace("@here", "@ here")`

**Comment by destruc7i0n** [comment]
Fixed that @everyone and @here problem, also added an option if you want to re-enable it.
