### ISSUE TITLE
discord wont recieve messages but will send.

### ISSUE THREAD

**Issue by ChonkyWonky** [destruc7i0n/shulker#44]
even when tailing latest.log (listening on 6969), discord can send but cant recieve messages from the server (1.14.1)

the error it gives when sending a message on the minecraft server is:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /</pre>
</body>
</html>

any help would be appreciated...

EDIT: i use discord canary instead of normal one dont know if that makes a difference tho

**Comment by ChonkyWonky** [comment]
fixed it lmao

**Comment by Qwerty-Space** [comment]
How did you fix this?

**Comment by ChonkyWonky** [comment]
Its been a really long time since i used shulker i forgot sorry 🙏
