### ISSUE TITLE
Local tail skips fast messages

### ISSUE THREAD

**Issue by UndarkAido** [destruc7i0n/shulker#48]
I have 7 people on the server and `/execute as @a run me is online` consistently shows only 5 messages in the chat.

**Comment by destruc7i0n** [comment]
Running on Windows or unix based? Pushed an update to use the native `watch` rather than `watchFile` which may have caused this.

**Comment by destruc7i0n** [comment]
closed with https://github.com/destruc7i0n/shulker/commit/417dfa990f1b085251bee137a745b4752f3b5dab and https://github.com/destruc7i0n/shulker/commit/8099fd7ac494c12860145f021c46326a1c784ea0
