### ISSUE TITLE
NPM Crash

### ISSUE THREAD

**Issue by Cholesterol** [destruc7i0n/shulker#5]
Not sure if this is shulker or discord.js but I've set up an implemented the package and am having the following crash intermittently.

http://pastebin.com/LAawtem2

Any tips appreciated - in the meantime setting up a script to run on a cronjob and kick it back alive every 30 minutes.

**Comment by destruc7i0n** [comment]
The problem is that the port is already in use or you don't have permission to bind that port. Try checking if there is something running on that port already.

Also try changing the listening port of the HTTP server or running the server as root using `sudo node index.js`.

**Comment by destruc7i0n** [comment]
@Cholesterol is this still happening?

**Comment by Cholesterol** [comment]
Hey there,

I actually circumvented it by setting a cronjob to restart it every 10 minutes... It happened mid-use randomly so it would be bound to that port already and then kick me out and give that error.  I don't have anything running on that port (checked and double checked).  I've solved my issue in a round about way so you can close this.

**Comment by destruc7i0n** [comment]
Actually, try using forever instead. This is very weird as this never happened to me and it has been running for over 2 days now flawlessly.

**Comment by Cholesterol** [comment]
it might have to do with the server restarting?  I'm running FTB Infinity Evolved so I have frequent restarts (every 3 hours) - the issue seems to crop up the most during those times as I can't continuously run the server without hitting memory leaks from all the crazy stuff we are doing.

**Comment by destruc7i0n** [comment]
That must be it, on restart MC creates a new log file, so the tail command breaks. I would suggest trying to fix those memory leaks...

**Comment by SecretOnline** [comment]
The tail command runs completely independently of the node portion of Shulker. The crash is probably caused by the RCON module not being able to connect. I'll quickly test this to see if it's the case.
