### ISSUE TITLE
The datapack does not show in my minecraft server  

### ISSUE THREAD

**Issue by DaveTheKing3** [destruc7i0n/shulker#69]
![image](https://user-images.githubusercontent.com/80597718/111040778-1081b080-8435-11eb-83fa-5ab1d314251e.png)

**Comment by destruc7i0n** [comment]
This is not a datapack, this is a script you would run on your server. Instructions are available in the readme.

**Comment by child-duckling** [comment]
Why do you think this is datapack? I'm interested....
