### ISSUE TITLE
Death message false positives

### ISSUE THREAD

**Issue by MageLuingil** [destruc7i0n/shulker#70]
The current keyword method of detecting death messages allows for false positives, such as this one:

![villager-death](https://user-images.githubusercontent.com/6116956/117722944-f8ad7b00-b19e-11eb-89c6-e0087ce6af59.png)

A more robust solution would use an actual regex to detect expected death messages at the beginning of the log line. I have a solution that's been running on my server for two weeks now with no apparent issues.  (Pull request incoming)

**Comment by destruc7i0n** [comment]
closed in #71
