### ISSUE TITLE
What have I done...

### ISSUE THREAD

**Issue by Keaft** [destruc7i0n/shulker#8]
I do:

git clone https://github.com/destruc7i0n/shulker.git
cd shulker
npm install

http://pastebin.com/yHsW9mSG

**Comment by destruc7i0n** [comment]
Weird... A new build proved nothing should have went wrong...

https://travis-ci.org/destruc7i0n/shulker

Can you provide more info about your environment etc?

**Comment by Keaft** [comment]
Linux jhserv1 3.16.0-57-generic #77~14.04.1-Ubuntu SMP Thu Dec 17 23:20:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

name@jhserv1:~/destruc7i0n/shulker$ npm --version
1.3.10

At some point I looked up an error code and installed node-legacy. 

Very possible that ubuntu 14.04 doesn't apt-get an updated node: npm WARN engine discord.js@5.3.2: wanted: {"node":">=0.12.7"} (current: {"node":"v0.10.25","npm":"1.3.10"})

Full install log:
http://pastebin.com/9HzcHJBp

**Comment by destruc7i0n** [comment]
I'd recommend trying to reinstall node, the version that worked for me was v0.12.7 (at the least).

Use [nvm](https://github.com/creationix/nvm) for easier installation :)

**Comment by Keaft** [comment]
Worked like a charm:
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

**Comment by Keaft** [comment]
Almost worked like a charm. Now this:

jacob@jhserv1:~/shulker$ npm start

> shulker@1.0.0 start /home/jacob/shulker
> node index.js

[INFO] Bot listening on *:8000
[INFO] Authenticated with 127.0.0.1:25575
[INFO] Recieved [20:20:45] [Async Chat Thread - #4/INFO]: <keaft> batmobile
TypeError: Cannot read property '1' of null
    at /home/jacob/shulker/index.js:62:43
    at Layer.handle [as handle_request] (/home/jacob/shulker/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jacob/shulker/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/jacob/shulker/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/jacob/shulker/node_modules/express/lib/router/layer.js:95:5)
    at /home/jacob/shulker/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/jacob/shulker/node_modules/express/lib/router/index.js:330:12)
    at next (/home/jacob/shulker/node_modules/express/lib/router/index.js:271:10)
    at IncomingMessage.<anonymous> (/home/jacob/shulker/index.js:45:9)
    at IncomingMessage.emit (events.js:104:17)

**Comment by SecretOnline** [comment]
You will need to edit your config.json.

There's a line that looks like 

`"REGEX_MATCH_CHAT_MC": "\\[Server thread/INFO\\]: <(.*)> (.*)",`

You will need to change it to something like

`"REGEX_MATCH_CHAT_MC": "\\[Async Chat Thread - #\\d/INFO\\]: <(.*)> (.*)",`

**Comment by Keaft** [comment]
Quote:
"Some people, when confronted with a problem, think
'I know, I'll use regular expressions.'
Now they have two problems."

I love that quote. :D Thank you for taking time out of your life to get that regex set up. Works like a charm.

**Comment by Keaft** [comment]
Sometimes there are 2 digits before info. I hope there wont be 3 digits.
"REGEX_MATCH_CHAT_MC": "\\[Async Chat Thread - #\\d{1,2}/INFO\\]: <(.*)> (.*)",

**Comment by Keaft** [comment]
Sometimes there are 3 digits before info:
`\\[Async Chat Thread - #\\d{1,3}/INFO\\]: <(.*)> (.*)`

**Comment by SecretOnline** [comment]
Not sure, but you may as well change the regex to

`\\[Async Chat Thread - #\\d+/INFO\\]: <(.*)> (.*)`

which will accept any number of digits, not just 1-3. I should have said that earlier, but I didn't think we'd end up in triple digits.
