### ISSUE TITLE
@ and maybe other symbol escaping?

### ISSUE THREAD

**Issue by Keaft** [destruc7i0n/shulker#9]
I tried to get my attention from minecraft in discord with "@keaft" like a pleb and,

http://pastebin.com/ZGzdp0An

Could be a function of the differing regex I'm using?

It crashes and closes shulker.

**Comment by SecretOnline** [comment]
That looks like an issue with discord.js. That stacktrace isn't giving me a lot to go on past that.

---

As a side note, Discord doesn't actually send `@username`, instead it sends `<@userid>` (and `<#channelid>` for channel mentions). It's the clients that then translate that and make it look like a user mention. You can see this if you do an @mention in Discord and see what happens in Minecraft.

If you want to @mention from Minecraft, you'll need a 'translator' that takes the `@username` and turns it into `<@userid>`

**Comment by Keaft** [comment]
Turns out this also occurs when someone edits a message in discord. I was running it under forever, and yet it still hangs for some reason on occasion. Currently running it under forever appears to assuage the issue, but I thought I would let you know anyway.

`[INFO] Recieved [02:43:06] [Async Chat Thread - #39/INFO]: <XanTHM> just gonna check me phone for that
[INFO] Recieved [02:43:10] [Async Chat Thread - #39/INFO]: <XanTHM> cya
/home/jacob/shulker/node_modules/discord.js/lib/Util/Cache.js:1
],old[this[discrimS]]);if(item){var index=this.indexOf(item);Object.assign(thi
                                                                    ^
TypeError: undefined is not a function
    at Cache.update (/home/jacob/shulker/node_modules/discord.js/lib/Util/Cache.js:1:2168)
    at WebSocket.websocket.onmessage (/home/jacob/shulker/node_modules/discord.js/lib/Client/InternalClient.js:64:439)
    at WebSocket.onMessage (/home/jacob/shulker/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:418:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/home/jacob/shulker/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:816:10)
    at /home/jacob/shulker/node_modules/discord.js/node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (/home/jacob/shulker/node_modules/discord.js/node_modules/ws/lib/Receiver.js:364:5)
    at /home/jacob/shulker/node_modules/discord.js/node_modules/ws/lib/Receiver.js:466:14
    at Receiver.flush (/home/jacob/shulker/node_modules/discord.js/node_modules/ws/lib/Receiver.js:340:3)
    at Receiver.opcodes.1.finish (/home/jacob/shulker/node_modules/discord.js/node_modules/ws/lib/Receiver.js:482:12)

npm ERR! Linux 3.16.0-69-generic
npm ERR! argv "/home/jacob/.nvm/versions/v0.12.7/bin/node" "/home/jacob/.nvm/versions/v0.12.7/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! shulker@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shulker@1.0.0 start script 'node index.js'.
npm ERR! This is most likely a problem with the shulker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls shulker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jacob/shulker/npm-debug.log
`

**Comment by Keaft** [comment]
So even forever doesn't seem to keep this up forever anymore.

http://pastebin.com/WsmRwxHk

I'm running: forever -e ./error.log start index.js
to capture the error log. You can see it manages to pull it back up from the same error over and over again, but for some reason unknown to me it eventually fails.

**Comment by destruc7i0n** [comment]
What are you doing on Discord throughout all these errors?

**Comment by Keaft** [comment]
So as far as replicatable behaviors:
I can trigger the error everytime if I edit a message in discord after I post it.

Other behaviors, which don't seem to effect it, include just straight up chatting and posting web links. 

Otherwise it seems to just happen over time.

**Comment by Keaft** [comment]
It appears I can also trigger it if I post a youtube link inside of minecraft.

**Comment by destruc7i0n** [comment]
That seems to be the way the tail is supposed to work... I cannot seem to replicate this error myself :/

**Comment by Keaft** [comment]
Is there a way I can get a more verbose error log. Maybe something that lists everything that is going on?

**Comment by destruc7i0n** [comment]
You can try enabling Debug in the config file.
